### ISSUE TITLE
Neo4j cypher query to Elasticsearch using Graphaware

### ISSUE THREAD

**Issue by ShreerakshaAchutha** [graphaware/neo4j-to-elasticsearch#107]
I have this example query which is in Neo4j Cypher.

"MATCH (tag:Tag {name: 'John_Rhys-Davies'})<-[:HAS_TAG]-(message:Message)-[:HAS_CREATOR]->(person:Person)
OPTIONAL MATCH (:Person)-[like:LIKES]->(message)
OPTIONAL MATCH (message)<-[:REPLY_OF]-(comment:Comment)
WITH person, count(DISTINCT like) AS likeCount, count(DISTINCT comment) AS replyCount, count(DISTINCT message) AS messageCount
RETURN
  person.id,
  replyCount,
  likeCount,
  messageCount,
  1*messageCount + 2*replyCount + 10*likeCount AS score
ORDER BY
  score DESC,
  person.id ASC
LIMIT 100"

I would like to know how can I write this Neo4j Cypher query in Elasticsearch using Graphaware procedures (For eg: CALL ga.es.queryNode('')).
I have been trying a lot but not able to find the solution so can someone help me in this?

**Comment by ikwattro** [comment]
Hi @ShreerakshaAchutha 

You have to pass an Elasticsearch query, the procedure accepts a query in json format. If you have difficulties to build an Elasticsearch query, please post this as a question on StackOverflow as example as this is not an issue.

Thanks.
