### ISSUE TITLE
Elastic Search 6.x Types

### ISSUE THREAD

**Issue by mobiengilani** [graphaware/neo4j-to-elasticsearch#108]
Hello, 

In the newest version of Elastic Search are types removed. Is there a way to transport a neo4j node to a Elastic Search index. So lets say we have a "Person" node in Neo4j, is there a way to sync that as a Person index in Elastic Search ?

Thankyou very much

**Comment by ikwattro** [comment]
Hi @mobiengilani 

Yes, you have to use the JsonMapper, documented here : https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md

There you can specify an index for every type of node you want.

**Comment by mobiengilani** [comment]
Great ! Thankyou very much
