### ISSUE TITLE
Mapping to entire document inside of _source instead of just the properties

### ISSUE THREAD

**Issue by DaveClissold** [graphaware/neo4j-to-elasticsearch#114]
The plugin maps an entire document into _source, including index, type and id, it does set the document _id and type correctly.  The mapped properties of the document are then contained within another object, 'source'. To access the mapped data is a call like this

_source.source.name 

instead of the expected

_source.name

Below are a screenshot of current format 
<img width="570" alt="current" src="https://user-images.githubusercontent.com/7284070/39811620-38b52c68-5381-11e8-827e-d1e39c2f88d6.png">

expected format
<img width="563" alt="expect" src="https://user-images.githubusercontent.com/7284070/39811623-3c3e48d8-5381-11e8-8898-75f869ef8e94.png">

**Comment by aftab0000** [comment]
I am having the same issue.

**Comment by noumaans** [comment]
@ikwattro - still seeing this issue on graphaware-neo4j-to-elasticsearch-3.4.0.52.8.jar

Can you please confirm if this fix was merged in the 3.4.0.52.8 release? Thanks.
