### ISSUE TITLE
Updating labels on a node is not handled correctly

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#12]
Consider the following case:
1) create a node X with 2 labels `["foo", "bar"]`
2) the plugin adds X in two labeled indices `"myprefix_nodes_foo"` and `"myprefix_nodes_bar"`
3) update node X: remove label `"bar"` and add label `"pie"`
4)  the plugin adds X in label index `"pie"`

Issue: X is not removed from labeled index `"bar"`.

Solution: When a node is updated:
1) perform a search query on all labeled indices filtered on the updated node's ID.
2) delete the node from indices it doesn't belong to anymore
3) add the node to indices that it should belong to

**Comment by ikwattro** [comment]
Thanks @davidrapin This is a known bug. Will be fixed in the next iteration

**Comment by davidrapin** [comment]
Good :)

**Comment by ikwattro** [comment]
Fixed by #21
