### ISSUE TITLE
BUG: After initialization updates delete docs

### ISSUE THREAD

**Issue by DaveClissold** [graphaware/neo4j-to-elasticsearch#120]
This is using the 3.3.3.52.9 snapshot that @ikwattro sent me on the Neo slack channel.  

Initialization is great and it handles the ES docs as expected with the fields all contained in _source. not in _source.source. However as soon as a document is updated in anyway it sends the ES update to _source.source

**Comment by ikwattro** [comment]
Fixed here, waiting for release https://www.dropbox.com/s/0o0sbjenudvox54/graphaware-neo4j-to-elasticsearch-3.4.0.52.9-SNAPSHOT.jar?dl=0

**Comment by ikwattro** [comment]
Released, available here : https://products.graphaware.com/download/neo4j-to-elasticsearch/graphaware-neo4j-to-elasticsearch-3.4.0.52.9.jar
