### ISSUE TITLE
can't search data in elasticsearch after update in neo4j 

### ISSUE THREAD

**Issue by sofiane01234** [graphaware/neo4j-to-elasticsearch#123]
@ikwattro  Hi sir  , 
i've integrated elasticsearch 6.2.4 with neo4j 3.4.0 using graphaware 
i'm using an external mapping file (mapping.json) , 
At the first time :  
- the index is created 
- the documents are indexed  

The problem is when updating a node in neo4j , the document is actually updated in elasticsearch but we can't reach it with _search query (elasticsearch). 
Is there any additional configuration to make document searchable after an update in elasticsearch ? 
Can anyone help please.

**Comment by sofiane01234** [comment]
Hi Again Mr @ikwattro  
i've checked the indexed document structure in elasticsearch before update , it looks like this :

```
 {
                "_index": "neo4j-index-node",
                "_type": "doc",
                "_id": "63ce5f70-6a4f-11e8-a75a-08d40c60a063",
                "_version": 4,
                "_score": 1,
                "_source": {
                    "index": "neo4j-index-node",
                    "type": "doc",
                    "id": "63ce5f70-6a4f-11e8-a75a-08d40c60a063",
                    "source": {
                        "fname": "lalalala",
                        "mname": "Test Test",
                        "type": "Member",
                        "email": "abcd@gmail.com"
                    }
                }
            },


```   


and after the update in neo4j , the document will be updated and re-indexed and will look like this 


```

 {
                "_index": "neo4j-index-node",
                "_type": "doc",
                "_id": "63ce5f70-6a4f-11e8-a75a-08d40c60a063",
                "_version": 4,
                "_score": 1,
                "_source": {
                    "index": "neo4j-index-node",
                    "type": "doc",
                    "id": "63ce5f70-6a4f-11e8-a75a-08d40c60a063",
                    "source": {
                        "fname": "lalalala",
                        "mname": "Test Test",
                        "type": "Member",
                        "email": "abcd@gmail.com"
                    }
                }
            },
```



is this structure normal ? or it's a bug ? 
Thanks in advance

**Comment by ikwattro** [comment]
Hi @sofiane01234 , it is a bug that has been fixed. You can use the snapshot here : https://www.dropbox.com/s/0o0sbjenudvox54/graphaware-neo4j-to-elasticsearch-3.4.0.52.9-SNAPSHOT.jar?dl=0 Will be publicly available with new release. Refers to #120
