### ISSUE TITLE
Capped result?

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-to-elasticsearch#127]
Hi, 
during an analysis of your wonderful plug-in it seems that the below funktion-call constantly returns 10 nodes 

CALL ga.es.queryNode('{\"query\":{\"match\":{\"text\":\"person\"}}}') YIELD node RETURN node

There are ~220 "text" that contains the word person.

Is this a feature, configuration issue or a bug?

**Comment by ikwattro** [comment]
Hi @AndreasHenningsson ,

This just proxies a real elasticsearch query to Elastic, so as Elastic is by default returning 10 results you would have to change the query exactly as you would query Elastic directly : 

For example, this query will return max 500 results:
```
CALL ga.es.queryNode('{"from": 0, "size": 500, "query":{"match":{"text":"person"}}}') 
YIELD node 
RETURN node
```

**Comment by AndreasHenningsson** [comment]
Tanks,

Is it possible to configure in mapping.json that a specific attribute should be replecated as a "date"?
Example from my test json file. The below attribute submit_date should preferably be a date-type. Right now it is beeing replecated as a string (when viewed in kibana).

{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "default-index-node",
    "relationships_index": "default-index-relationship",
    "include_remaining_properties": true
  },
  "node_mappings": [
    {
      "condition": "hasLabel('doc')",
      "index": "nodes-doc",
      "type": "documents",
      "properties": {
        "Status": "getProperty('Status')",
	"DocNumber": "getProperty('DocNumber')",
	"Priority": "getProperty('Priority')",
	"Service_Type": "getProperty('Service_Type')",
	"Submit_Date": "getProperty('Submit_Date')"
      	}
    }
  ],
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "relationships"
    }
  ]
}

**Comment by ikwattro** [comment]
@AndreasHenningsson Can you give me an example value ?

**Comment by AndreasHenningsson** [comment]
Yes the value is stored as follows:
Submit_Date: 2018-07-01 13:01:03

**Comment by ikwattro** [comment]
So, it is correct and should be sent as a string. Your Elastic mapping should define it as a date field : https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html

**Comment by ikwattro** [comment]
Can you paste here your ES mapping for that particular index.

**Comment by ikwattro** [comment]
Tested with Elastic 6.3, if you have a well defined `date` type for a field and try to pass a wrong format, such as the one without seconds, it will fail : 

```
ikwattro@mbp666 ~/d/_es> http POST http://localhost:9200/my_index/_doc/1 < doc.json -v
POST /my_index/_doc/1 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 31
Content-Type: application/json
Host: localhost:9200
User-Agent: HTTPie/0.9.9

{
    "date": "2015-01-01 12:10"
}

HTTP/1.1 400 Bad Request
content-encoding: gzip
content-length: 194
content-type: application/json; charset=UTF-8

{
    "error": {
        "caused_by": {
            "reason": "Invalid format: \"2015-01-01 12:10\" is malformed at \" 12:10\"",
            "type": "illegal_argument_exception"
        },
        "reason": "failed to parse [date]",
        "root_cause": [
            {
                "reason": "failed to parse [date]",
                "type": "mapper_parsing_exception"
            }
        ],
        "type": "mapper_parsing_exception"
    },
    "status": 400
}
```

**Comment by AndreasHenningsson** [comment]
Ok, that said neither 2018-07-01 13:01:03 or 2018-07-01 13:01 is a valid format

So, how should a datafield in neo look like in order to get the type "date" i elastic?

I think a meet the beelow critera 

Sorry for bothering you :-)

-----------------------------
JSON doesn’t have a date datatype, so dates in Elasticsearch can either be:

strings containing formatted dates, e.g. "2015-01-01" or "2015/01/01 12:10:30".
a long number representing milliseconds-since-the-epoch.
an integer representing seconds-since-the-epoch.

**Comment by AndreasHenningsson** [comment]
Can I assign a format of the attribute in mapping.json?

**Comment by ikwattro** [comment]
@AndreasHenningsson closing this as it is not an issue with the plugin. Please continue to comment on the ticket if you have further questions

**Comment by AndreasHenningsson** [comment]
Thanks for the help!

tors 5 juli 2018 kl. 13:45 skrev Christophe Willemsen <
notifications@github.com>:
