### ISSUE TITLE
auto complete field elastic search 

### ISSUE THREAD

**Issue by sofiane01234** [graphaware/neo4j-to-elasticsearch#130]
Hi Sir @ikwattro , 

i am implementing the auto complete feature in elastic search with graphaware 
i need to add the type "completion" in one of index properties ( see code ) 

```
 "properties" : {
                "suggest" : {
                    "type" : "completion"
                }
}
```

is there any solution to do this ? 
Thanks in advance

**Comment by sofiane01234** [comment]
Hello again @ikwattro 
what you propose to me it does not work..
what I did is to create the mapping of the index directly on elasticsearch with the type completion on the attribute suggest, and then I index the documents from the file mapping.json, in fact I when indexing I filled in the "weight" and "input" fields of the suggest attribute manually, as mentioned below : 

 ```
"properties": {

                "suggest" :  "query('RETURN {input:[\"Medical Doctors\"  , \"Dentists\"], weight : 25 } AS value')"	,
				
            }
```
conculsion: it does not work when we create the index via mapping.json, we must first create it directly on elasticsearch, then load the data from mapping.json

Sincerly

**Comment by ikwattro** [comment]
Hi @sofiane01234 ,

To be clear, our plugin creates an index if it doesn't exist, but will not create the index mapping ( ES ) for you.

Maybe a clarification is needed in the documentation about the `mapping` word, the mapping.json file you are using in Neo4j is intended only for definition your replication logic.

The mapping in Elasticsearch should be defined and created by you for your own search needs, this module is only intended at replicating to Elasticsearch and knowledge about how Elasticsearch works is on your side.

Cheers

Christophe
