### ISSUE TITLE
Elasticsearch and neo4j

### ISSUE THREAD

**Issue by Arcturus999** [graphaware/neo4j-to-elasticsearch#135]
Hi guys,
I've been using Linkurious along with Elasticsearch and Neo4j for quite some time now, but I've recently been having issues with Neo4j's queries. The error is the following

``{"level":"error","message":"server.services.webServer.api TECHNICAL:critical ElasticSearch: Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.es.queryNodeRaw`: Caused by: java.lang.RuntimeException: Error while performing query on ElasticSearch. Query was (..)``

It shows up each time I try to search something.
I've seen this #132 and I think it's quite similar to what I have, but since upgrading neo in our prod's environnement would take some time, I was wondering is there's any way to bypass the timeout setting.

Thanks for your help :)

**Comment by ikwattro** [comment]
Hi @Arcturus999 ,

In order to help you better, it would be nice to post the neo4j logs relevant to when the error happens.

Thanks

**Comment by davidrapin** [comment]
Hi @Arcturus999, please get in touch with us (Linkurious) directly using the Linkurious support email, we will give you instructions on how to solve this.

**Comment by Arcturus999** [comment]
Hey, @davidrapin thanks for your reply. I will get in touch with you very soon. @ikwattro it seem that Neo4j doesn't show any errors, neither does ES ( except the time when it didn't have enough memory, I was at least able to query something in Link, but the messages still showed ).
