### ISSUE TITLE
Neo4j to Elastic search bulk operation failing via the graphaware plugin.

### ISSUE THREAD

**Issue by gjerin594** [graphaware/neo4j-to-elasticsearch#136]
In our scenario, we have data similar to syslog / monitoring metrics that are continuously collected and posted to Neo4j. This data is then pushed to ES using the graphaware plugin. Over the last few days, we have started noticing an error with the bulk operations from Neo4j while pushing to ES. Could you please help in resolving the issue? 

In the JVM options file we have set the values of the java heap size to 40GB. However, even after increasing the size of the Java Heap the issue is seen to persist. 

I have attached a copy of the Neo4j configuration file, jvm options file and a snippet of the error we are receiving
[jvm_options.txt](https://github.com/graphaware/neo4j-to-elasticsearch/files/2388790/jvm_options.txt)
[neo4j_conf.txt](https://github.com/graphaware/neo4j-to-elasticsearch/files/2388765/neo4j_conf.txt)
[neo4j_error.txt](https://github.com/graphaware/neo4j-to-elasticsearch/files/2388777/neo4j_error.txt)

We are using 
1. Neo4j-3.3.0
2. ElasticSearch - 5.6.4
3. Graphaware Plugin :
    a.  graphaware-neo4j-to-elasticsearch-3.3.0.51
    b. graphaware-server-community-all-3.3.0.51
    c. graphaware-uuid-3.3.0.51

**Comment by gjerin594** [comment]
Hi @ikwattro , Could you please help out with this issue? We are losing very precious data as well as time as the issue seems to still persist. Thanks in advance!

**Comment by gjerin594** [comment]
I did go through https://github.com/graphaware/neo4j-to-elasticsearch/issues/42 and i did try the steps mentioned there. Our ES heap size was increased and the queue size was decreased for Neo4j from 10000 to 1000. The error is still persisting.

**Comment by ikwattro** [comment]
Based on your errors, the plugin cannot connect to your ES instance. Can you make a curl request to the ES cluster ?

**Comment by gjerin594** [comment]
@ikwattro - Yes. I am able to curl to the ES instance. It is hosted on the same machine. We have already pushed around 90000+ records from Neo4j to ES successfully. Over the last two weeks however, we have had issues with the push from Neo4j to ES.

**Comment by ikwattro** [comment]
Try to disable bulk, there will be more logging regarding the issue.

**Comment by gjerin594** [comment]
@ikwattro . Will do that and get back with the results. Much thanks!

**Comment by gjerin594** [comment]
Hi @ikwattro , we are still testing on the issue and are facing issues. The bulk mapping is now disabled. Is there any way that we can do a refresh operation? For eg: The data is present in Neo4j but it is absent in Elastic search due to bulk push failure. Would there be any way, we can refresh the data so that the missing data is mapped via the plugin?

**Comment by gjerin594** [comment]
@ikwattro Thanks for the prompt response! Will check it out.

**Comment by ikwattro** [comment]
@gjerin594 any update ?
