### ISSUE TITLE
Nodes with multiple labels duplicated in search results

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#14]
Since nodes are stored in ES once per label (with a different `_type` for each label), multiple documents will be created if the node has many labels.
As a consequence:
- a search query matching a node with multiple labels will have the multi-labeled node duplicate in the results
- pagination of results becomes difficult to handle because it is impossible to predict how many actual **unique** nodes will be returned by a search query with `"size":10` (worst case: 1 node duplicated 10 times because it has 10 labels)

**Comment by davidrapin** [comment]
This can be solved by creating an alternative mapping that doesn't have the side-effect of storing nodes with multiple categories multiple times.

**Comment by ikwattro** [comment]
Fixed by #21
