### ISSUE TITLE
[BC] Port all mappings to JsonMapping

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-to-elasticsearch#141]
The future of this plugin is to move all configurations to the JsonMapping, the current basic and default configurations will be moved to internal json mapper files shipped with the plugin.

cc @davidrapin 

Minimum ES compat will be 6.x, so one type per index

I do not expect much BC breaks in terms of the behaviors, but the neo4j.conf file will have to be adapted accordingly.

**Comment by davidrapin** [comment]
Thank you for the heads up.
We are planning on deprecating the use of the plugin with Linkurious starting with Neo4j 3.5 since this version integrates full-text search natively.
Can you wait until Neo4j 3.5 before suppressing Linkurious’s specific mapping?

**Comment by ikwattro** [comment]
@davidrapin No worries, as I said the current mapping definitions will remain for a while, but as json shipped as resources.

I believe the first neo4j2es version shipping with this BC will be our first 3.5 version tho.
