### ISSUE TITLE
404 error when executing against ES

### ISSUE THREAD

**Issue by DaveClissold** [graphaware/neo4j-to-elasticsearch#148]
Not sure why or how, but started to see a loss of data in the ES docs, was keeping things like image urls, but numerical information and some query based mappings we being lost, so checked the neo4j logs and saw this flooding them

```
Failed to execute an action against Elasticsearch. Details: 404 Not Found
```
Had to restart the database to stop this from continuing. Any idea why all of a sudden this would come up or can you shed some light on the error? ES instance is running fine, can query and write to the ES isntance ok. 

Running neo 3.5 and the 3.5 of the plugin

**Comment by ikwattro** [comment]
Hi @DaveClissold 

I think I would need more context, that log might be that a node is `updated` but the document does not exist yet in ES. Are there any `ES` logs when this happens ?
