### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by leagleag** [graphaware/neo4j-to-elasticsearch#150]
Hello,
I am trying to connect both Neo4j and ES and despite my efforts I am stuck on this error:
```
ERROR Failed to create Elasticsearch index. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9201 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
```
I posted some details on this [post](https://stackoverflow.com/questions/55424652/connection-refused-connecting-neo4j-es-docker-containers-with-graphaware) since the issue might not be specifically related to graphaware.

Thanks for your help

**Comment by ikwattro** [comment]
Closing this issue. The answer in the SO post is the right path to solving your problem. I suggest you read more about how Docker works in general.
