### ISSUE TITLE
failed to start neo4j service 

### ISSUE THREAD

**Issue by nickjhmd** [graphaware/neo4j-to-elasticsearch#157]
when i firstly ran neo4j.bat console, it is ok
but latter neo4j service cannot be started

**Comment by nickjhmd** [comment]
![image](https://user-images.githubusercontent.com/33509765/66255637-9ddcc200-e7b8-11e9-991f-dfd47e6bc202.png)

**Comment by aldrinm** [comment]
which jdk/jre version are you using ?

**Comment by nickjhmd** [comment]
the jdk version is 12

> which jdk/jre version are you using ?

**Comment by aldrinm** [comment]
Neo4j is only supported up to Java 11 (as runtime). See https://neo4j.com/docs/operations-manual/current/installation/requirements/

**Comment by nickjhmd** [comment]
> Neo4j is only supported up to Java 11 (as runtime). See https://neo4j.com/docs/operations-manual/current/installation/requirements/

thanks a lot
