### ISSUE TITLE
Enable indexing relationships

### ISSUE THREAD

**Issue by bachmanm** [graphaware/neo4j-to-elasticsearch#16]
...the same way nodes are indexed

**Comment by davidrapin** [comment]
Done. My PR is ready to be pushed but I'm waiting for #15 to be merged first.

**Comment by bachmanm** [comment]
Done - go for it :) Thanks a lot for your contributions, they look good!

**Comment by davidrapin** [comment]
Thank you @bachmanm :)

**Comment by davidrapin** [comment]
@bachmanm quick question about GraphAware plugins configuration: is there a documentation for inclusion policies' text representation? 
I'm looking to a way to express `IncludeAllBusinessRelationships` and `IncludeNoRelationships` in the configuration file.

**Comment by davidrapin** [comment]
Ops, never mind, I just found the `com.graphaware.common.policy.spel` package :)

**Comment by bachmanm** [comment]
cool - also: https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies

**Comment by bachmanm** [comment]
Essentially if you want all or none, just use the FQN of the policy and not the SPeL expression

**Comment by davidrapin** [comment]
Ah yes, I just found out where the black magic happens :)
https://github.com/graphaware/neo4j-framework/blob/master/runtime/src/main/java/com/graphaware/runtime/config/function/StringToInclusionPolicy.java

**Comment by davidrapin** [comment]
Interestingly, setting `com.graphaware.module.ES.relationship=false` fails since `StringToInclusionPolicy` tries to resolve a class called `true`, but using `com.graphaware.module.ES.relationship=(true)` works like a charm (while suboptimal).

**Comment by davidrapin** [comment]
Created a PR for this as it seems like something useful to have: https://github.com/graphaware/neo4j-framework/pull/52

**Comment by davidrapin** [comment]
@bachmanm would you prefer to keep relationship indexing disabled by default or changing to enabled by default?

**Comment by davidrapin** [comment]
@bachmanm Also, I'll need to change the current Cypher procedure (remove `"query"`) and create two distinct `"queryNode"` and `"queryRelationship"` procedures, does that work for you?

**Comment by bachmanm** [comment]
I think I would prefer not indexing relationships by default, but it's not a strong preference. Something like "queryNode" and "queryRelationship" works for me. Thanks!

**Comment by davidrapin** [comment]
Ok!

I just ran into a issue: `ElasticSearchProcedure` uses `GraphDatabaseService#findNode(Label, String, String)` to resolve nodes by label+uuid, is there any equivalent for relationships? I can't find it and start wondering if I'm looking in the wrong place.

**Comment by davidrapin** [comment]
@ikwattro Thanks for your anwser on StackOverflow :) I'm wondering about the best way to access `getNodeByUuid` and `getRelationshipByUuid` from the neo4j-to-elasticsearch module. Any ideas?

**Comment by ikwattro** [comment]
I think you can access the uuid module like I did in the PR for es2neo on this line :


https://github.com/graphaware/neo4j-to-elasticsearch/pull/13/files#diff-568c405b4e8598a5603bc93adcaf5b60R150 <https://github.com/graphaware/neo4j-to-elasticsearch/pull/13/files#diff-568c405b4e8598a5603bc93adcaf5b60R150>

Sorry I’m on the way to Amsterdam, let me know if you succeed

**Comment by davidrapin** [comment]
@ikwattro Thank you, it works :) PR incoming!

**Comment by davidrapin** [comment]
Ok, PR #18 is ready for review :)
