### ISSUE TITLE
io.searchbox.action.Action exception for 3.5.14 version

### ISSUE THREAD

**Issue by m00dy** [graphaware/neo4j-to-elasticsearch#160]
Hello, 

I believe that I followed the steps correctly to integrate this project into neo4j. 

Neo4j version 3.5.14
-rwxrwxrwx 1 ereyag ereyag 13983881 Feb 20 12:08 graphaware-server-all-3.5.14.55.jar
-rwxrwxrwx 1 ereyag ereyag    75642 Jan 14 09:43    neo4j-to-elasticsearch-3.5.14.55.10.jar
-rwxrwxrwx 1 ereyag ereyag    27299 Jan 14 09:43    uuid-3.5.14.55.19.jar

kg-neo4j | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.graphaware.runtime.bootstrap.RuntimeKernelExtension@3a022576' was successfully initialized, but failed to start. Please see the attached cause exception "io.searchbox.action.Action".
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
kg-neo4j | 	at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
kg-neo4j | 	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:443)
kg-neo4j | 	... 15 more
kg-neo4j | Caused by: java.lang.NoClassDefFoundError: io/searchbox/action/Action
kg-neo4j | 	at com.graphaware.module.es.ElasticSearchConfiguration.<clinit>(ElasticSearchConfiguration.java:37)
kg-neo4j | 	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:52)
kg-neo4j | 	at com.graphaware.module.es.ElasticSearchModuleBootstrapper.defaultConfiguration(ElasticSearchModuleBootstrapper.java:31)
kg-neo4j | 	at com.graphaware.runtime.module.BaseRuntimeModuleBootstrapper.bootstrapModule(BaseRuntimeModuleBootstrapper.java:60)
kg-neo4j | 	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.registerModules(RuntimeKernelExtension.java:143)
kg-neo4j | 	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.start(RuntimeKernelExtension.java:113)
kg-neo4j | 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
kg-neo4j | 	... 22 more
kg-neo4j | Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
kg-neo4j | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
kg-neo4j | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
kg-neo4j | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
kg-neo4j | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)

is anyone familiar with this issue ?

If I disable this line in the configuration, 
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper
it bootstraps, but in this case I can't see indexes on elasticsearch.

**Comment by seweissman** [comment]
I had this issue today. It seems like there are some dependencies that didn't get bundled into the jar. I was able to download an earlier version and get it to work: https://repo1.maven.org/maven2/com/graphaware/neo4j/neo4j-to-elasticsearch/3.5.6.54.11/neo4j-to-elasticsearch-3.5.6.54.11.jar

**Comment by m00dy** [comment]
hey @seweissman, thanks for the tip. I will try it tomorrow asap :)

**Comment by seweissman** [comment]
Actually @m00dy it looks like maybe the 3.5.6 jar isn't compatible with the newer graphaware-server-all releases, so I'm not sure this is really a working solution. Hopefully someone can update the jars so they work.

**Comment by m00dy** [comment]
I pulled the recent version from maven and I think it works.

wget https://repo1.maven.org/maven2/com/graphaware/neo4j/neo4j-to-elasticsearch/3.5.14.55.10/neo4j-to-elasticsearch-3.5.14.55.10.jar

**Comment by seweissman** [comment]
Thanks. This worked for me too!

**Comment by lpanichi** [comment]
Could be nice to have a fix for this because the plugin is bundled in a docker image in my environment and this make the system harder to maintain and test :s

**Comment by DanielJamieson** [comment]
Just to make this absolutely clear to the maintainers - this issue still exists.

When using the JAR for version `3.5.14.55.10` that is hosted on Maven (the one which @m00dy has linked to) - it works no problems without this error.

However if you try to use the same JAR from https://products.graphaware.com/ - then we get the `io.searchbox.action.Action` exception. Looks like the JAR has been rebuilt with the right dependencies, but it hasn't been uploaded to the right place for the graphaware site.
