### ISSUE TITLE
Neo4j database switch support

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#2]
What is the current/expected behavior when Neo4j is stopped and the `graph.db` folder is replaced with another one (another database)?

**Comment by alenegro81** [comment]
You need to empty also the ES.

**Comment by davidrapin** [comment]
@alenegro81 Cloud you please answer my question which was: what is the current behavior when this happens?

**Comment by bachmanm** [comment]
Well, your Neo4j database will be empty and your Elasticsearch will have data in it that points to non-existing nodes in the database...

**Comment by davidrapin** [comment]
@bachmanm Thank you Michal. I was wondering if you took advantage or the neo4j ` StoreId` to detect a store switch and trigger a re-indexing.

**Comment by bachmanm** [comment]
Not really, I don't think people typically just throw away their databases, but if it's important for you guys, please create a feature request

**Comment by davidrapin** [comment]
I was not thinking about throwing away the database but rather having multiple databases (lets say `graph1.db` , `graph2.db`) in the `data` folder and switching them by changing the value of `org.neo4j.server.database.location` in `neo4j-server.properties`.

This is pretty common in my experience. I'll create a feature request with a precise use-case :)
