### ISSUE TITLE
replication mapping questions

### ISSUE THREAD

**Issue by foobargeez** [graphaware/neo4j-to-elasticsearch#27]
I ran into the neo4j->ES replication blog [post](http://graphaware.com/neo4j/elasticsearch/2016/07/27/advanced-neo4j-to-elasticsearch-replication.html) and got introduced to replication mapping file.  I didn't find documentation regarding where to create the file and the possible configuration options/syntax.  I would appreciate if you can point me to additional docs, if any.

Thanks in advance!

**Comment by ikwattro** [comment]
Hi,

The doc is here https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md

The README still needs to be updated though
