### ISSUE TITLE
Option of providing multiple elastic search indexes

### ISSUE THREAD

**Issue by vganjare** [graphaware/neo4j-to-elasticsearch#28]
Hi,

Currently, we can specify the ES index using following configuration:
com.graphaware.module.ES.index=neo4j-index

Is it possible to specify which Graph DB needs to be copied into which ES index? e.g. lets say I am having two different Graph DBs (within single instance of GraphDB) 
1. **users.db** located at C:/neo4j/data/users.db
2. **data.db** located at C:/neo4j/data/data.db

I want to copy users.db data into ES index neo4j-users and data.db data into ES index neo4j-data.

Is it possible to have this feature in Graphaware module?

Thanks,
Vishal

**Comment by ikwattro** [comment]
You cannot run two databases at the same time, so you can just modify the configuration before starting the database
