### ISSUE TITLE
Which Neo4j versions are supported?

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#3]
I could not find a Neo4j/Neo4j2Elastic version compatibility matrix in the readme.

**Comment by bachmanm** [comment]
As with all GraphAware Framework modules, you can read the supported version number from the module's version number (https://github.com/graphaware/neo4j-to-elasticsearch#note-on-versioning-scheme)

For ES, we're using Jest 1.7.0, so whatever that's compatible with... I'd have to investigate.

**Comment by davidrapin** [comment]
Ok thank you :)
