### ISSUE TITLE
Relationship index questions

### ISSUE THREAD

**Issue by foobargeez** [graphaware/neo4j-to-elasticsearch#31]
Loving the flexibility in the latest connector version -- thanks for the effort!

Couple of questions:
- Does the connector support storing relationship labels via getLabels()?  I tried updating in mapping.json but I couldn't get it working (if supported, I could be missing something obvious), but I first wanted to check if this is supported to begin with.
- How do I store the connecting node UUIDs for relationships (source node and dest node) in Elasticsearch?

The above, if supported/implemented lets me do some interesting aggregations against Elasticsearch.

Thanks in advance!

**Comment by ikwattro** [comment]
Hi @foobargeez 

Relationships do not have labels but rather a `type`, you can get it with the `getType()` method.

Currently the relationship data doesn't offer the possibility to have access to the start and end node objects, note that this would require opening a transaction for retrieving it. However this is a feature we want also and we are investigating to provide this information from an upfront layer, I will open an issue regarding this.

**Comment by foobargeez** [comment]
> Relationships do not have labels but rather a type, you can get it with the getType() method.

Thanks.  Is there a place I can find all supported functions, say getType()/allRelationships()/etc.,?  That will be a great self-help doc.

> Currently the relationship data doesn't offer the possibility to have access to the start and end node objects, note that this would require opening a transaction for retrieving it. However this is a feature we want also and we are investigating to provide this information from an upfront layer, I will open an issue regarding this.

Thanks.  If I didn't already mention, you guys rock!

**Comment by ikwattro** [comment]
There is some doc here : 

https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md

Otherwise I'll make sure all those are documented in the future. We are already modifying the framework for getting the start and end node, so I'll update all at once.

**Comment by ddebaill** [comment]
Hi ikwattro

What about the framework evolution regarding start and end node ?
When do you plan to deliver a fixed documentation ?

Thanks ;)

**Comment by ikwattro** [comment]
Point 1 should have been solved.

Point 2 no bandwith yet

**Comment by ddebaill** [comment]
Hi Christophe

Thanks; is there a specific configuration in order to get start and end node on relationships ? I use the latest version of the framework and within ES, neo4j-index-relationship index, I don't see any information related to connected nodes.

Thanks

**Comment by foobargeez** [comment]
Hi ddebaill,
I use something alone the below lines in my mapping.json to get start and end node properties that I care to get indexed in Elasticsearch:

```
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "getType()",
      "properties": {
        "startNodeUUID": "getStartNode().getProperty('uuid')",
        "endNodeUUID": "getEndNode().getProperty('uuid')",
        "endNodeName": "getEndNode().getProperty('name')",
        "endNodeLabels": "getEndNode().getLabels()",
      }
    }
```

I hope it helps!

**Comment by ddebaill** [comment]
Hi foobargeez

Will try; keep you informed, thanks
