### ISSUE TITLE
neo4j-to-elasticsearch integration fails for Data added using Neo4j Batch Import

### ISSUE THREAD

**Issue by vganjare** [graphaware/neo4j-to-elasticsearch#36]
Hi,

I am using Neo4j Batch Import to add the data from CSV in neo4j (https://neo4j.com/developer/guide-import-csv/#_super_fast_batch_importer_for_huge_datasets). The added data is not getting replicated in the Elastic Search. I can see that the uuid field is getting added to all the nodes (added using batch import). Is there any additional setting needs to be done to use neo4j batch import?

UPDATE: Running a set operation on all the nodes causes the data to be copied in ElasticSearch.

Thanks,
Vishal

**Comment by bachmanm** [comment]
Neo4j Batch import bypasses transactions in Neo4j. It does not use a running Neo4j in fact, just writes to disk. Hence no modules kick in. You have two options:

1) Insert the data into a running Neo4j database
2) Use Neo4j Batch import and configure the module to index all the stuff in the DB when it first starts - look at the docs and search for `initializeUntil` to see how to do that.
