### ISSUE TITLE
JsonMappingException: Can not deserialize instance

### ISSUE THREAD

**Issue by sebolek** [graphaware/neo4j-to-elasticsearch#38]
I'm having trouble when using custom mapping file with Neo4j-to-elasticsearch: this is the error i get when trying to start Neo4j

2016-08-13 00:32:53.848+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Unable to bootstrap module 2 Unable to read json mapping file
java.lang.RuntimeException: Unable to read json mapping file
	at com.graphaware.module.es.mapping.JsonFileMapping.configure(JsonFileMapping.java:53)
	at .....

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: /home/abc/neo4j-community-3.0.4/conf/mapping.json; line: 24, column: 57] (through reference chain: com.graphaware.module.es.mapping.json.DocumentMappingRepresentation["node_mappings"]->com.graphaware.module.es.mapping.json.GraphDocumentMapper["properties"])

I believe this is what's causing the error:
line: 24, column: 57 is "
"postal_code":  
               { "postal":"getProperty('Postal Code')", "type":"string", "analyzer":"stop" },"

Here is my entire JSON mapping file:
{  
   "defaults":{  
      "key_property":"uuid",
      "nodes_index":"rets-node",
      "relationships_index":"rets-node-relationship",
      "include_remaining_properties":false
   },
   "node_mappings":[  
      {  
         "condition":"hasLabel('Property')",
         "type":"listings",
         "properties":{  
            "full_address":"getProperty('Address')",
            "building_address":"getProperty('Address Number')+ ' '+getProperty('Address Direction')+ ' ' +getProperty('Address Street')+ ' ' +getProperty('Street Designation') + ', '+getProperty('City')",
            "unit_number":"getProperty('Address Unit')",
            "city":"getProperty('City')",
            "community":"getProperty('Sub-Area/Community')",
            "street_name":"getProperty('Address')",
            "age":"getProperty('Age')",
            "mls":"getProperty('ML #')",
            "zoning":"getProperty('Zoning')",
            "area":"getProperty('Area')",
            "complex":"getProperty('Complex/Subdivision')",
            "agent1":"getProperty('LA1Agent Full Name')",
            "postal_code":  
               { "postal":"getProperty('Postal Code')", "type":"string", "analyzer":"stop" },
            "style_of_home":"getProperty('Style of Home')",
            "type_of_dwelling":"getProperty('Type of Dwelling')",
            "prop_type":"getProperty('Prop Type')",
            "price":"getProperty('List Price')",
            "office_name":"getProperty('LO1Office Name')",
            "municipality":"getProperty('Municipality')",
            "lot_size":"getProperty('Lot Sz (Sq.Ft.)')",
            "mgmt_company":"getProperty('Mgmt. Co Name')",
            "seb_date_added":"getProperty('seb_date_added')",
            "seb_status":"getProperty('seb_status')",
            "system_id":"getProperty('System ID')",
            "beds":"getProperty('Total Bedrooms')",
            "baths":"getProperty('Total Baths')"
         }
      }
   ]
}

Any ideas would be greatly appreciated.

Thanks!
Seb

**Comment by alenegro81** [comment]
Did you try removing nested document?

**Comment by sebolek** [comment]
nested document? can you be more precise.

**Comment by alenegro81** [comment]
I mean a plain structure with no nested element like post_code.

**Comment by sebolek** [comment]
Yes, it works fine when I remove the nested element "postal_code", but how else do I specify/map that this field needs to be index as "not analyzed"? basically I'm trying for Elasticsearch to index multi-words like "V6Y 4E4", without it elasticsearch indexes each word separately.

**Comment by foobargeez** [comment]
The mapping needs to be changed on the ES side -- you can index a field in multiple ways as specified in mappings.  I use the following in my mapping file"

                    "Other names": {
                        "match_mapping_type": "string",
                        "match": "Other names",
                        "mapping": {
                            "type": "string",
                            "fields": {
                                "raw": {
                                    "type": "string",
                                    "index": "not_analyzed",
                                    "ignore_above": 256
                                },
                                "lowercased": {
                                    "type":      "string",
                                    "analyzer":  "lowercase_keyword",
                                    "index":     "analyzed"
                                }
                            }
                        }
                    }

I use `Other names.lowercased` when I want to search for exact string in a case _insensitive_ manner and `Other names.raw` when I want to search the string in an _exact_ manner etc.,

Hope it helps!

**Comment by sebolek** [comment]
What do you mean by "The mapping needs to be changed on the ES side"? I thought the only way to configure mappings for "neo4j-to-elasticsearch" is in the mapping file which resides in the neo4j conf folder? and yes that's exactly what i need "not analyzed and case insensitive index"

**Comment by foobargeez** [comment]
> What do you mean by "The mapping needs to be changed on the ES side"?

This may help -- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html.

> I thought the only way to configure mappings for "neo4j-to-elasticsearch" is in the mapping file which resides in the neo4j conf folder?

The connector's `mapping.json` is broadly telling what to store in the index but __how__ to index per your requirements needs to be configured in Elasticsearch.

Hope this helps!

**Comment by sebolek** [comment]
Thanks for pointing me in the right direction foobargeez, i got it all almost figured out now ;)

Seb

**Comment by ikwattro** [comment]
@foobargeez Thanks for helping !
