### ISSUE TITLE
neo4j-to-elasticsearch integration fails for Elasticsearch with Shield Plugin

### ISSUE THREAD

**Issue by vganjare** [graphaware/neo4j-to-elasticsearch#4]
Hi,

I am using neo4j-to-elasticsearch integration for my ElasticSearch node which is having Shield plugin installed. Currently, all the ElasticSearchWriter request fails with following error:

`14:45:48.227 [GraphAware Starter] ERROR c.g.module.es.ElasticSearchWriter - Failed to create Elasticsearch index. Details: {"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/neo4j-index]"," header":{"WWW-Authenticate":"Basic realm=\"shield\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/neo4j-index]","header":{"WWW-Authenticate":"Basic realm=\"shield\""}}`

Is there any way to pass on the authentication information?

Thanks,
Vishal

**Comment by akash10agarwal** [comment]
Hey Vishal, I guess you should look for something known as Allow Cross
Origin/Domain Policy on the internet.It might solve your issue.

Regards,
Akash

Regards,
Akash Agarwal

PESIT,Bangalore
+919632126630

**Comment by bachmanm** [comment]
good feature request, I don't think we can do this today... @alenegro81 ? :)

**Comment by alenegro81** [comment]
working on this ...

**Comment by vganjare** [comment]
Hi,

Do we have any timeline for this feature? Also, I am using ElasticSearch Version 2.3.1

Thanks,
Vishal

**Comment by alenegro81** [comment]
we have just released the new version that support basic auth for shield. Have a look at it

**Comment by ikwattro** [comment]
Available here http://products.graphaware.com/download/neo4j-to-elasticsearch/latest

**Comment by vganjare** [comment]
Thanks a lot for quick response. Code changes looks great.

Thanks,
Vishal
