### ISSUE TITLE
Remove dependency of neo4j-uuid

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-to-elasticsearch#47]
If we use our own uuid strategy, we still need to add the `neo4j-uuid` jar as it is marked as provided in the pom.

Find a way to abstract and remove this dependency.

cc @davidrapin @alenegro81

**Comment by davidrapin** [comment]
This particular point is solved in my PR :)

**Comment by ikwattro** [comment]
@davidrapin I didn't found it solved because there is no way to specify from the configuration which id resolver to use (nb: I would prefer to specify the class name of the resolver to use like we do for the mapping). But happy to look back to it once there are some tests and feel free to remove the uuid dependency in the pom in your PR then.
