### ISSUE TITLE
Sorting give some json error

### ISSUE THREAD

**Issue by tomswinkels** [graphaware/neo4j-to-elasticsearch#48]
Hi,

When we want search for some words like "CALL ga.es.queryNode('{"from":0,"size":50,"query":{"match":{"message":"someren asten"}}}') YIELD node return node" it works.

Now we want to sort the results by sended(timestamp). I have read the documentation of Elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html) and i think this command must be work "CALL ga.es.queryNode('{"from":0,"size":50,"query":{"match":{"message":"someren asten"}},"sort":[{"sended":{"order":"desc"}}]}') YIELD node return node" but i get the following error.

**Neo.ClientError.Procedure.ProcedureCallFailed:**
Failed to invoke procedure `ga.es.queryNode`: Caused by: java.lang.UnsupportedOperationException: JsonNull

We hope that any can help us :)

**Comment by ikwattro** [comment]
Hi, do you have anything in the elasticsearch logs ? Did you tried this query first directly against elasticsearch ?

**Comment by ikwattro** [comment]
@tomswinkels neverming, it seems we had an issue on this.

Can you please test the fix version here https://www.dropbox.com/s/lpzqy4pkj3mglhb/graphaware-neo4j-to-elasticsearch-3.0.6.43.7-SNAPSHOT.jar?dl=0

**Comment by tomswinkels** [comment]
Yeah, very nice! :)
