### ISSUE TITLE
Publish indexing obejct in RabbitMQ

### ISSUE THREAD

**Issue by Zenithar** [graphaware/neo4j-to-elasticsearch#50]
In order to dispatch indexing process according ES nodes, It would be great to publish all indexing messages in a RabbitMQ queue.

**Comment by ikwattro** [comment]
We have some plans for that, but not as part of this module. Basically our plan would dispatch json representations of the `TransactionData` object to a message broker. The kind of brokers we would support would be abstracted with a concrete implementation for kafka, not sure if we gonna maintain and support rabbitmq ourself but writing an implementation will be easy.

I cannot give a time when this will be released though as it depends highly on our current workload which is quite heavy at the moment.
