### ISSUE TITLE
Does this plugin support automatic synchronization as data is changed?

### ISSUE THREAD

**Issue by sandyplace** [graphaware/neo4j-to-elasticsearch#51]
Does this plugin re-index when a node is changed after a transaction has committed? Or does it re-index on server startup? In other words does it keep the elasticsearch index in synch in realtime as nodes and relationships are created/updated/deleted or is it triggered manually?

**Comment by bachmanm** [comment]
Yes, it keeps ES index in sync in near-real-time by sending updates after tx commits

**Comment by mazorigal** [comment]
Hi,

small question, does the neo4j-to-elasitcsearch plugin based on the improved transaction event API (https://github.com/graphaware/neo4j-framework/tree/master/tx-api) ?

Thanks
