### ISSUE TITLE
Indexing Relationships first time module is launched

### ISSUE THREAD

**Issue by renanstuchi** [graphaware/neo4j-to-elasticsearch#52]
Hello guys,

I couldnt find an answer to this question, so im asking here. Maybe i m doing something wrong: is there any kind of issue trying to index relationships at the first time module is launched? 
I think this feature is important if somethings goes wrong with elastic server at the time data was created in neo4j and it couldnt replicate data.

When i launch the module first time everything works fine with 'Nodes', but none relationship are indexed. Also If i create new data in neo4j everything works fine with Nodes and Relationships, and i got it replicated to elastic.
But i cant figure out how to index relationships at the moment module is launched first time.

Am i doing anything wrong?

My conf:

```
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper
com.graphaware.module.ES.uri=localhost
com.graphaware.module.ES.port=9200
com.graphaware.module.ES.keyProperty=uuid
com.graphaware.module.ES.retryOnError=false
com.graphaware.module.ES.queueSize=10000
com.graphaware.module.ES.node=
com.graphaware.module.ES.relationship=(true)
com.graphaware.module.ES.bulk=true
com.graphaware.module.ES.initializeUntil= --currentMillis--

com.graphaware.module.ES.mapping = com.graphaware.module.es.mapping.JsonFileMapping
com.graphaware.module.ES.file = mapping.json
```

And mapping.json

````
{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "neo4j-index-node",
    "relationships_index": "neo4j-index-relationship",
    "include_remaining_properties": true
  },

 "node_mappings": [
      // all node code 
    ]
  "relationship_mappings": [
    {
      "condition": "isType('LIKE')",
      "type": "LIKE"
    },

    {
      "condition": "isType('HUB')",
      "type": "HUB",
	  "properties": {
		  "relationshipType": "getProperty('relationshipType')"  }
    },

    {
      "condition": "isType('CONTACT')",
      "type": "CONTACT",
	  "properties": {
		  "status": "getProperty('status')"  }
    }
  ]
}```

**Comment by ikwattro** [comment]
Can you specify the neo4j version and modules you are using, also can you confirm you have `uuids` on your relationships ?

**Comment by renanstuchi** [comment]
hello @ikwattro .

Neo4j 3.0.7
ElasticSearch 2.4.0

Yes, i m using UUID on relationships too.

`com.graphaware.module.UIDM.uuidProperty=uuid
com.graphaware.module.UIDM.relationship=(true)
com.graphaware.module.UIDM.uuidIndex=uuidIndex
com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex`

**Comment by agdelen** [comment]
hi @bachmanm, @ikwattro,

I have been investigating the mentioned problem and today i decided to look at the source code. Then I suddenly realised that on **ElasticSearchModule.java** file the if statement which is responsible for reindexing relationships is empty.

Then I decided to fork the project, made the necessary change, then build and finally use the plugin and check if its working.

You can check **my one line addition** from [this](https://github.com/leadtimeapp/neo4j-to-elasticsearch/commit/be8fd919c0922cff4c61b63205187bcf833050b8) commit.

After i successfully built the plugin when i set **com.graphaware.module.ES.initializeUntil** parameter as needed, it reindexes the whole relationships.

I wonder if there is a reason you did not make that development. Did you leave that if statement deliberately?

**Comment by ikwattro** [comment]
Hi @agdelen , very sorry for this, seems like it was omitted somehow. Will be fixed in next release.

**Comment by agdelen** [comment]
Hi @ikwattro, thanks for the fix.
