### ISSUE TITLE
Is it possible define Types for properties ?

### ISSUE THREAD

**Issue by renanstuchi** [graphaware/neo4j-to-elasticsearch#56]
Hello,

Sorry i couldnt find an answer for my doubt. Is it possible to define types for properties? Like this:
"properties": {
        "myTextField":"getProperty('myTextField')"  { "type":  "text" },
        "myKeyField": "getProperty('myKeyField')"  {"type":  "keyword"}
 }

Thanks in advance.

**Comment by ikwattro** [comment]
No it isn't possible, you would have to create your ES mapping separately. Also if you want to convert neo4j properties to specific types, you would be able to do it using java methods, for example : 

```
"numberAsTextField": "Integer.valueOf(getProperty('editionNumber'))"
```

But there is no knowledge of specific ES types like keyword or text.

**Comment by renanstuchi** [comment]
Ty for answer @ikwattro .
So every single property mapped to elastic will be type "text", right?
But what if i want to use Term Query ? From what i saw here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html 

...depending of your query and term u are searching use Term Query on a property "text" is a bad approach.
Sorry if i missunderstood anythin, i am new to elastic and i m having the same problem listed on link above. My property contains a text that needs match a exact value (thats why i tried to use Term Query) but since i cant define it as "keyword" it is being analyzed and breaking my text value.

Thanks again

**Comment by ikwattro** [comment]
No, you are mixing `indexing` and `searching`.

There are two mappings to take into account here : 

1. The mapping that defines WHAT to index from neo4j to elastic
2. Your Elasticsearch specific mapping

For 1, we just say take this property from a node and send it for indexing to Elasticsearch with for this particular ES field. Properties in neo4j that are integers are sent as integers, String properties are sent as strings.

For 2, if your ES mapping is defining that the field X should be number and the property is text, then there will be an issue.

For querying ES, I wouldn't recommend to pass by this plugin, especially if you have no experience with ES so far.
