### ISSUE TITLE
HTTPS support to Elasticsearch

### ISSUE THREAD

**Issue by owulff** [graphaware/neo4j-to-elasticsearch#57]
Add support for https connection for Elasticsearch.

As described [here](https://github.com/searchbox-io/Jest/blob/master/jest/README.md) the following change is required:

  JestClientFactory factory = new JestClientFactory();
  factory.setHttpClientConfig(new HttpClientConfig.Builder("https://localhost:9200")
                .defaultSchemeForDiscoveredNodes("https") // required, otherwise uses http
                .sslSocketFactory(sslSocketFactory) // this only affects sync calls
                .httpsIOSessionStrategy(httpsIOSessionStrategy) // this only affects async calls
                .build()

**Comment by ikwattro** [comment]
Will be added during next upgrades. Thx.

**Comment by owulff** [comment]
Do you have already a rough idea when?

Our project wants to go productive end of february.

**Comment by ikwattro** [comment]
No idea sorry, we would accept definitely a PR with tests. Thanks

**Comment by agdelen** [comment]
I have added https connection support but i have not wrote any tests yet. So i could not send any PR to master branch yet but i will send as soon as i finish writing the tests.

If there is anyone who wants to use [here](https://github.com/leadtimeapp/neo4j-to-elasticsearch) is my fork and [this](https://github.com/leadtimeapp/neo4j-to-elasticsearch/commit/c104c1385f41f994db883acaf79a6d512b93046f) is the commit i made

**Comment by ikwattro** [comment]
Thanks @agdelen Feel free to make a PR as it is. I will take care of the tests.

**Comment by Zhenshan-Jin** [comment]
@agdelen Thanks for adding the https connection support.
@ikwattro Thanks for the great library to link Neo4j and Elasticsearch, for which, I think, should be one software, called NeoElastic. I'm currently working with your library and want to build a productive software based on it, but the same problem would be the https connections. I'm wondering does neo4j-to-elasticsearch have make any plan to built this feature into the library? Thanks!

**Comment by Zhenshan-Jin** [comment]
@ikwattro Thank you for the quick response of @agdelen 's PR pull request, https://github.com/graphaware/neo4j-to-elasticsearch/pull/94 
Looking forward to the HTTPS features of this beautiful library

**Comment by ikwattro** [comment]
Fixed by #94
