### ISSUE TITLE
Neo4j HA compatibility

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#58]
Are there any caveats/limitations in using this plugin with Neo4j HA?
My approach would be to install the plugin in the Neo4j master only, any problem with that?

**Comment by bachmanm** [comment]
Yep, if master dies, your replication stops. You should deploy on all machines, only master accepts transactions in Neo, hence no problem with running it on slaves too.

**Comment by davidrapin** [comment]
Thanks a lot @bachmanm !

**Comment by ikwattro** [comment]
we should upgrade the `Neo4jToElasticsearchConfiguration` though so that it triggers only on masters. Plan in next iteration.
