### ISSUE TITLE
Option to store Relationships as Nested Objects

### ISSUE THREAD

**Issue by CerebralUnit** [graphaware/neo4j-to-elasticsearch#59]
I have a case where I have user profiles in Neo4j that have the relationship [:SPEAKS]. The node (:User) and the node (:Language) are connected through this relationship. I currently don't see a way to query languages in elasticsearch and join that query with the User docs. Elasticsearch supports a form of joining using the 'nested' or 'has_child/parent' queries. 

It would be nice to have a flag that, when set, mapped Language node docs to be stored as a child to the User if the relationships [:SPEAKS] exists between the two nodes. Then searching for 'French' would return all Users who speak French. Currently, the only workaround for this functionality that I can see is duplicating the User's data as a set of properties on every relationship.

**Comment by ikwattro** [comment]
Hi @CerebralUnit That is a very interesting request. We'll investigate about a nice solution to get this done.

**Comment by tomswinkels** [comment]
Good idea!

**Comment by Dannybevers** [comment]
Like this option! Got the same issues with my data and likely to combine my data in nested objects! :)

**Comment by tomswinkels** [comment]
@ikwattro is there any update about this question. For now we have fixed with a extra node (Container) in Neo4j. But this is a temporary fix not for longtime.

**Comment by ikwattro** [comment]
This is now implemented, you can use cypher queries as replication logic. Check https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md
