### ISSUE TITLE
Indexing is not working on elastic search 5.2

### ISSUE THREAD

**Issue by balajiforgithub** [graphaware/neo4j-to-elasticsearch#62]
Hi,

I have followed all the instructions that were mentioned , but unable to start neo4j server  after making these changes. Could someone please assist to resolve this issue.

Software versions : 
 Neo4j Community edition 3.1.1
 Elastic Search 5.2
 Neo4j-ElasticSearch-3.1
 Operating system : Windows 7 professional (64 bit)

Error : Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@9db196a' was successfully initialized, but failed to start.

**Comment by omarlarus** [comment]
hi @balajiforgithub , can you provide us the full stack trace log, please?

Thanks,
Omar
