### ISSUE TITLE
Option to get count

### ISSUE THREAD

**Issue by tomswinkels** [graphaware/neo4j-to-elasticsearch#63]
Hi There,

Is there some option to get the total count of the results in Elastic Search of is there any other option to get the count?

With this code i get only a count of 10. 
`CALL ga.es.queryNode('{"sort":[{"sended":{"order":"desc"}}],"filter":{"bool":{"must":{"type":{"value":"TS_P2000MessageContainer"}}}}}') YIELD node
RETURN count(node)`

**Comment by szenyo** [comment]
Hi @tomswinkels ,
what about queryNodeRaw?
If you use that, then you get the output as json. And you can use APOC to get the result easily.
Try something like this:
CALL ga.es.queryNodeRaw('{"sort":[{"sended":{"order":"desc"}}],"filter":{"bool":{"must":{"type":{"value":"TS_P2000MessageContainer"}}}}}') YIELD json RETURN apoc.json.path(json,"$.hits.total")
