### ISSUE TITLE
No results when insert an new result in neo and get to fast data from elastic

### ISSUE THREAD

**Issue by tomswinkels** [graphaware/neo4j-to-elasticsearch#69]
Hi there,

When we insert an new result into Neo4j and running directly an query with "CALL ga.es.queryNodeRaw" we get sometimes not results. When we are wait a half second than we get it.

So i think when we running the query "CALL ga.es.queryNodeRaw" the Graphaware plugin must check if there are running processes and waiting for give the result back.

So for me this is an very big problem, i hope that any can help me :)

**Comment by tomswinkels** [comment]
@ikwattro i hope that you can help me :)

**Comment by ikwattro** [comment]
@tomswinkels well, generally documents in Elasticsearch are available for search 1 second
after it has been indexed (shard is refreshed).

Reference : 

https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html#refresh-api

What you can do : 

a) refresh the shard manually
b) query the document by id ( documents are available for query by id in the cache )

**Comment by tomswinkels** [comment]
@ikwattro thanks for you're fast answer. How can i do an query by id?

**Comment by ikwattro** [comment]
There is no procedure for it in our module (might come though), best is to query ES directly.
