### ISSUE TITLE
Neo4j 3.2.0 support

### ISSUE THREAD

**Issue by Artgit** [graphaware/neo4j-to-elasticsearch#71]
Does neo4j-to-elasticsearch supports Neo4j 3.2.0 ? If no, when do you plan to add this ?

**Comment by ikwattro** [comment]
A couple of days

**Comment by Artgit** [comment]
is there any news on this ?

**Comment by davidrapin** [comment]
It's released now: https://products.graphaware.com/?dir=neo4j-to-elasticsearch
