### ISSUE TITLE
Synchronize the Neo4j and ES state

### ISSUE THREAD

**Issue by Artgit** [graphaware/neo4j-to-elasticsearch#72]
I have desynchronized the state between my Neo4j server and ES.

I have manually dropped the database(physically removed the database files from disk) and after that I have reimported data into my Neo4j database.

Right now at ES I have a data duplication - 2 documents for every single node at Neo4j.  

What is a proper way right now to sync the data between my Neo4j and ES in order to leave at ES only the valid nodes ?

Thanks.

**Comment by ikwattro** [comment]
There is no standard way for doing this and definitely nothing is built-in this module to achieve this.

The best idea would be to create a new index into ES and re-index your neo4j database : 

* increate the initializeUntil
* restart neo4j
