### ISSUE TITLE
Question regarding ensuring parity between Neo4j and Elasticsearch

### ISSUE THREAD

**Issue by john-bodley** [graphaware/neo4j-to-elasticsearch#75]
Less of an issue and more of a question. We're using Neo4j in conjunction with Elasticsearch where the search indexes are managed via this GraphAware plugin.

In general things work fairly well though over time we've noticed there's creep in the system and now the number of documents in the Elasticsearch cluster greatly exceed the number of entities in the Neo4j graph database. 

I speculate there's a few reasons for this: 
- We've had issues in the past with bulk loading with custom mappings and thus have stopped/re-started Neo4j on several occasions with different configuration systems.
- As part of a daily ETL job we perform bulk updates to our graph where the majority of entities are either created, deleted, or updated. Given that this plugin is based on event triggers over time I suspect it's not surprising there's discrepancies in the counts. 

So my questions are:
1. Is this behavior observed frequently by others in production environments?
2. What steps should one take to best ensure that the Elasticsearch indices closely mimic the Neo4j database?
3. If this behavior is not unheard of, how do most people deal with these discrepancies, i.e., is it common to purge the Elasticsearch indices with erroneous entries? 

For us ideally we would love to only actively manage the Neo4j database and allow the plugin to provide a passive symbiotic relationship with the Elasticsearch cluster, though parity between the two is key. Given we already have an ETL pipeline we could potentially bypass the plugin and simply create and populate an Elasticsearch index on a daily basis which would roughly ensure parity with Neo4j on a daily basis, though we would sacrifice the realtime functionality the plugin provides.

**Comment by ikwattro** [comment]
Hi @johnbodley 

Very good question.

* Neo4j reboots shouldn't affect the number of documents in Elasticsearch as long as uuids are not re-generated and this uuid is used as document id in ES.
* The internal queue system isn't persistent, meaning that if Neo4j goes down, pending graph updates are not certained to reach ES.

Solutions and how others manage this scenario : 

This highly depends on the size of the graph and the already infrastructure in place. Some clients can live with a system down for a small amount of time where a new index will be created and neo4j restarted with the reinitialize value on.

Some other clients where the graph is a critical part of the system or the time a full re-index would take is too long, we generally move over to kafka.

What does it means for this plugin ?

We worked the last months for a client where we replaced the synchronous updates with rather pushing those updates to a kafka topic and a consumer was indexing them in ES. This has worked pretty well and offers also a serious amount of other advantages (more complex mappings, scaling the consumers during high load and more importantly a persistent system between Neo and ES). We plan to release publicly this kafka integration along with its consumer during the summer, this would then be a matter of changing the mapper class name in the configuration for neo4j-to-elasticsearch as well as providing the kafka host and topic name.

KR.

Christophe

**Comment by johnbodley** [comment]
Thanks @ikwattro for the response and insights. We've definitely had instability issues in the past with our configuration though thankfully the system has stabilized with upgrades to Neo4j, plugins, and drivers.

One question I have is does the re-index clear the Elasticsearch indexes before the indexes are re-populated with all the relevant Neo4j entities?

I think our next step is probably to purge all irrelevant documents from Elasticsearch and monitor any discrepancies over time, looking at both missing documents and obsolete documents.

With every Elasticsearch paginated result set we do perform a Neo4j search to gather additional graph context and thus at no additional cost we can filter out any obsolete records from the Elasticsearch search, i.e. perform an inner join. I think for us the concern is merely having an Elasticsearch index which isn't overly polluted and grow in a compounded manner over time.

Ideally our system should be up 24/7 but doing a reindex on a weekly basis, like at 12 am on Saturday might be a good compromise. Alternatively a cron to purge obsolete records could work.

Looking forward to seeing the Kafka work. The various GraphAware plugins had definitely been hugely beneficial for our work.

**Comment by ikwattro** [comment]
No it doesn't delete the index before the re-index (though this could be easily added) but ES itself provide a useful mechanism to migrate to new indexes (alias), basically your search would point to an alias rather than to a specific index. An alias is bound to one index, if you have to re-index, you create a new index with the data and then change your alias configuration.

**Comment by camelliazhang** [comment]
I have a similar questions. I noticed that if I delete all the nodes in graph, the elastic search still has the documents. Is this expected behavior with bridge? How do I make sure the data is consistent between neo4j and elastic search? @ikwattro

**Comment by siddhu93** [comment]
I have a same question asked by @camelliazhang. Please tell us how to handle data purging in ElasticSearch @ikwattro

**Comment by ikwattro** [comment]
@siddhu93 @camelliazhang Deleting nodes should delete documents, I have not seen this issue before, if you can re-create a setup that shows the issue, for eg with docker then I would be happy to look at it.
