### ISSUE TITLE
getDegree()/isOutgoing() funcitons don't work in mapping.json

### ISSUE THREAD

**Issue by Shawn-Zhenshan-Jin** [graphaware/neo4j-to-elasticsearch#79]
Neo4j Version: 3.2.2
Operating System: Ubuntu 16.04

I use `getDegree()` function in mapping.json file, but the return would always be `null`; I'm using the dataset neo4j tutorial Movie/Actor dataset.

**Output from elasticsearch request**
![nodes](https://user-images.githubusercontent.com/14370804/28997751-ff859e6a-79e1-11e7-90ff-633649e5824e.png)
**mapping.json**
```
{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "default-index-node",
    "relationships_index": "default-index-relationship",
    "include_remaining_properties": true
  },
  "node_mappings": [
    {
      "condition": "hasLabel('Person')",
      "type": "getLabels()",
      "properties": {
        "getDegree": "getDegree()",
        "getDegree(type)": "getDegree('ACTED_IN')",
        "getDegree(direction)": "getGegree('OUTGOING')",
        "getDegree('type', 'direction')": "getDegree('ACTED_IN', 'OUTGOING')",
        "getDegree-degree": "degree"
      }
    }
  ],
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "type",
    }
  ]
}
```

Also if I use `isOutgoing(), isIncoming(), otherNode` function in relationship_mappings properties part, elasticsearch would never load the relationship data from neo4j. I think I probably have some misunderstanding of this sentence `only when one of the participating nodes "looking" at the relationship is provided` on this page [https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies](url)

**mapping.json**
```
{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "default-index-node",
    "relationships_index": "default-index-relationship",
    "include_remaining_properties": true
  },
  "node_mappings": [
    {
      "condition": "allNodes()",
      "type": "getLabels()"
    }
  ],
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "type",
      "properties": {
        "isOutgoing": "isOutgoing()",
        "isIncomming": "isIncomming()",
        "otherNode": "otherNode"
      }
    }
  ]
}
```

BTW, is there any page that list all of the functions that we can use in mapping.json? I know two of them 

1. https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies
2. https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md
**but** it seems there are more, since I can use `getType()`, which hasn't been listed in any of the above pages.

Please let me know if I can provide any further help to solve the problem
Thanks!

**Comment by ikwattro** [comment]
Replied on StackOverflow : 


https://stackoverflow.com/a/45525899/2662355
