### ISSUE TITLE
Node with no labels are not indexed

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#8]
If a node does not have any labels, [its does not get indexed](https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/src/main/java/com/graphaware/module/es/executor/RequestPerOperationExecutor.java#L87).

To fix that, a solution would be index nodes with no labels with a placeholder _type, like `"_neo2es_no_label"`.

**Comment by alenegro81** [comment]
This could be an idea

**Comment by alenegro81** [comment]
we could also define a "default" index for unlabeled entry

**Comment by ikwattro** [comment]
I'm +1 for an index, `types` are becoming deprecated in ES and considered bad practices in 85% of the use cases right now.

**Comment by davidrapin** [comment]
@ikwattro Types are not deprecating in Elastic. Here is an interesting perspective on the pros and cons of indices vs. types: https://www.elastic.co/blog/index-vs-type.

If you end up using multiple indices, please use a common prefix for the index names in order to allow index wildcard searches, e.g. `GET http://localhost:9200/myprefix_*/_search`.

**Comment by ikwattro** [comment]
From us last partner training in february, the perspective taken by ES in the future CAN completely remove types at all. As of now, even the ES trainings don't teach you types as we would have use them in the past (they just put the type name the same as the index). Of course on big use case for types is for parent child mapping.

**Comment by ikwattro** [comment]
Now, my usage of this plugin makes me think more and more than there should be a better configuration definition, like xml mapping for eg, be in the oss framework or enterprise.

**Comment by ikwattro** [comment]
Fixed by #21
