### ISSUE TITLE
Elasticsearch can't sync 2GB database from neo4j with GprahAware

### ISSUE THREAD

**Issue by Zhenshan-Jin** [graphaware/neo4j-to-elasticsearch#80]
The neo4j2elasticsearch works on my machine when the database is only 250KB. But the the databse is around 2GB. It won't sync anymore. I'm wondering is because of these parameters in the config file:
```
optional, size of the in-memory queue that queues up operations to be synchronised to Elasticsearch, defaults to 10000
com.graphaware.module.ES.queueSize=10000
    
optional, size of the batch size to use during re-initialization, defaults to 1000
com.graphaware.module.ES.reindexBatchSize=2000
````

I'm wondering what is the unit of in-memory queue size 10000 and how to estimate what parameter to set based on my database size. 

Here is the debug file for 2GB failure loading :
![largedata_graphaware](https://user-images.githubusercontent.com/14370804/29049471-c42aebde-7b9b-11e7-8dcf-b040184c105a.png)

The database is **re-initialized** but there are only empty neo4j-index-relationship/neo4j-index-node index in the elasticsearch database

Just for information, here is the debug file for successful 250KB database loading:
![largedata_good](https://user-images.githubusercontent.com/14370804/29049480-d0c42f54-7b9b-11e7-9c58-6062842fb1ae.png)

seems like **Re-indexing nodes...** step is missing in the 2GB database loading procedure.

**Comment by vganjare** [comment]
Hi Team,

When I update large number of nodes in Neo4j, I am getting following error. How can this be resolved:

`"code": "Neo.DatabaseError.Transaction.TransactionCommitFailed",
      "message": "Service is not running!",
      "stackTrace": "java.lang.IllegalStateException: Service is not running!\n\tat com.graphaware.writer.thirdparty.BaseThirdPartyWriter.offer(BaseThirdPartyWriter.java:91)\n\tat com.graphaware.writer.thirdparty.BaseThirdPartyWriter.write(BaseThirdPartyWriter.java:79)\n\tat com.graphaware.runtime.module.thirdparty.WriterBasedThirdPartyIntegrationModule.afterCommit(WriterBasedThirdPartyIntegrationModule.java:52)\n\tat com.graphaware.runtime.module.thirdparty.WriterBasedThirdPartyIntegrationModule.afterCommit(WriterBasedThirdPartyIntegrationModule.java:30)\n\tat com.graphaware.runtime.manager.BaseTxDrivenModuleManager.afterCommit(BaseTxDrivenModuleManager.java:228)\n\tat com.graphaware.runtime.TxDrivenRuntime.afterCommit(TxDrivenRuntime.java:88)\n\tat com.graphaware.runtime.TxDrivenRuntime.afterCommit(TxDrivenRuntime.java:39)\n\tat org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:149)\n\tat org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:47)\n\tat org.neo4j.kernel.impl.api.TransactionHooks.afterCommit(TransactionHooks.java:75)\n\tat org.neo4j.kernel.impl.api.KernelTransactionImplementation.afterCommit(KernelTransactionImplementation.java:663)\n\tat org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:604)\n\tat org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:463)\n\tat org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.commit(TransitionalTxManagementKernelTransaction.java:94)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.closeContextAndCollectErrors(TransactionHandle.java:245)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:153)\n\tat org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:121)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:748)\n"



Thanks,
Vishal

**Comment by ikwattro** [comment]
We didn't expected such use case, I would be happy to investigate if you send us a backup of your db. Closing for now.
