### ISSUE TITLE
Unable to force a reindex of neo4j data into ElasticSearch

### ISSUE THREAD

**Issue by emoDino** [graphaware/neo4j-to-elasticsearch#83]
I have run into an issue where my Neo4j database and ElasticSearch cluster are desynchronized.

My ES cluster got wiped out which had all of the indices of my database. I stood up another ES stack, but when I restart neo4j, it just creates the new indices in the new cluster without actually indexing the data that exists. The ES indices are empty and I am unable to resynchronize my data.

Neo4j thinks that ElasticSearch has all of the data since it had in the past already synchronized the indices.

Is there any process/procedure to reset the state of your neo4j database to remove the neo4j-to-elasticsearch metadata? Is there a process to force a reindex of your data onto a fresh ES cluster?

**Comment by alenegro81** [comment]
Hi,
you can use initializeUntil configuration parameter selecting a previous long timestamp to force initialization
