### ISSUE TITLE
Graphaware 3.2.x plugin compatibility issue with Neo4j 3.3.0. Future plans?

### ISSUE THREAD

**Issue by vishwajitmankar** [graphaware/neo4j-to-elasticsearch#88]
We are planning to migrate to Neo4j 3.3.0 version. However, graphaware plug-ins are not yet released for the same. When I try to use graphaware-neo4j-to-elasticsearch-3.2.5.51.7 and other 2 plugins, I get below errors. Is there way to fix this issue with some settings or need to wait for next plugin version to release. Thank you in advance. 

2017-11-01 09:48:11.906+0000 ERROR Failed to start Neo4j: Starting Neo4j failed:
 Component 'org.neo4j.server.database.LifecycleManagingDatabase@5ef5c734' was su
ccessfully initialized, but failed to start. Please see the attached cause excep
tion "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/ut
il/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
 Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDa
tabase@5ef5c734' was successfully initialized, but failed to start. Please see t
he attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Lja
va/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphd
b/config/BaseSetting;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.n
eo4j.server.database.LifecycleManagingDatabase@5ef5c734' was successfully initia
lized, but failed to start. Please see the attached cause exception "org.neo4j.k
ernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Funct
ion;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStart
upError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111
)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)

        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32
)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.s
erver.database.LifecycleManagingDatabase@5ef5c734' was successfully initialized,
 but failed to start. Please see the attached cause exception "org.neo4j.kernel.
configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Lj
ava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSu
pport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.fact
ory.GraphDatabaseFacadeFactory, D:\eclipse\sw\neo4j-community-3.3.0-2\data\datab
ases\graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(G

**Comment by ikwattro** [comment]
It generally takes some time before we release for the latest neo versions. It will take a couple of days.

**Comment by vishwajitmankar** [comment]
Thank you. Will wait for latest version of this plugin before Neo4j upgrade.

**Comment by vishwajitmankar** [comment]
I see new Graphaware plugin with version 3.3.0. Will it work with elasticsearch-2.4.1 or we need to upgrade ES too?
I took all latest jars graphaware-neo4j-to-elasticsearch-3.3.0.51.7, graphaware-server-community-all-3.3.0.51, graphaware-uuid-3.3.0.51.14
I am getting below error -
2017-11-20 13:57:02.411+0000 ERROR Failed to create Elasticsearch index. org.apa
che.http.conn.HttpHostConnectException: Connect to localhost:9201 [localhost/127
.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Conne
ct to localhost:9201 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Co
nnection refused: connect
        at com.graphaware.module.es.mapping.BaseMapping.lambda$createIndexAndMap
ping$15(BaseMapping.java:184)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:18
4)

Thanks.

**Comment by vishwajitmankar** [comment]
If I understood the logic of version, for latest plugin, I will need Elasticsearch 51.7? (Which is not available.)

**Comment by sonu27** [comment]
@vishwajitmankar It's not related to ES. It's an internal build number I think.

Anyway the latest version does work with 3.3, so this can be closed.

**Comment by vishwajitmankar** [comment]
I tried with latest version of ES 6.0 and it worked. I had to change connecting port in neo4j.conf to 9200. It was working with 9201 with previous ES version and I was trying with same setting. 
We can mark this issue as close. Thank you so much for the support.
