### ISSUE TITLE
Monitor the status of the plugin via an API

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#9]
Since the plugin can put the Neo4j database and the ES index in unstable states (while creating UUIDs or doing a full indextion) it would be useful to have an API endpoint to check the current status of the plugin.

Something like:
GET `/graphaware/neo2es/status` => 
 - `{"status": "creating_uuids"}` 
 - `{"status": "indexing"}`
 - `{"status": "ready"}`

**Comment by alenegro81** [comment]
What do you mean for unstable status? Moreover the uuids are created before commit the transaction to the database. Indexing is a process that occur in batch, and could aggregates more commits in one batch. 
We can show indexing if the size of the queue is greater than 0 and ready otherwise.

**Comment by davidrapin** [comment]
When the plugin is installed on a existing Neo4j database, my understanding is that:
 1) First, the UUID plugin will create UUIDs for all existing nodes and relationships.
 2) Then, all existing nodes and relationships will be added in batch to ElasticSearch (initialization of the index triggered by `com.graphaware.module.ES.initializeUntil`).

Until these two steps are completed, the ES index in out of sync and all searches will return incomplete results. An API to check that these steps are undergoing would be nice.

@alenegro81 You mentioned being able to read the the indexing queue size (when syncing new changes from Neo4j). This could be nice too, but was not the point of my question.

**Comment by ikwattro** [comment]
@davidrapin @alenegro81 @bachmanm I have to disagree a bit. What you describe in point 1 and 2 are a use case of a completely passive neo4j database. Most of running databases have continuous updates and chances are that the queue size will be mainly continuously > 0, hence the Elasticsearch index can be considered always out of sync imo.

I would better see an endpoint returning a boolean representing the completion of the `initialization` process, can de done with a graph property, a node or maybe a static variable in the module itself.

**Comment by davidrapin** [comment]
@ikwattro Maybe I haven't been clear but this is exactly what I was trying to describe!

An API endpoint (or graph property) returning the status of the initialization as a boolean. As long as the value can be retrieved using the Cypher or REST endpoints, this fits our requirements.

**Comment by ikwattro** [comment]
Fair enough ! This would definitely be a nice addition !

**Comment by ikwattro** [comment]
@bachmanm Maybe this can be at the framework level though ?

**Comment by davidrapin** [comment]
@ikwattro I get an error when trying to use the procedure (the neo4j logs indicate that the plugin is loaded and the index was created):

`Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `ga.es.initialized` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed`

Am I missing something?

**Comment by ikwattro** [comment]
@davidrapin which version of the plugin are you using ?

**Comment by davidrapin** [comment]
The current version (built from master).

**Comment by ikwattro** [comment]
This is weird, I'll try to install it locally. Normally this test should cover the procedure call : 

https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/src/test/java/com/graphaware/module/es/proc/ElasticSearchModuleEndToEndProcTest.java#L136

But gimme a bit to test it locally

**Comment by ikwattro** [comment]
@davidrapin Are other procedures working ?

**Comment by ikwattro** [comment]
Allright, was a mismatch in my dbs.

So its working for me : 

![screen shot 2016-06-27 at 13 42 18](https://cloud.githubusercontent.com/assets/1222009/16378596/07d6b88c-3c6d-11e6-9ac5-3727f174589c.png)

**Comment by ikwattro** [comment]
@davidrapin  So can you output the output of the plugins directory ?

**Comment by davidrapin** [comment]
Procedures for the ES plugin are not working, but procedures for other plugins are working (e.g. `CALL ga.uuid.findNode('24685af0-3c5e-11e6-98d2-38c98626833b') YIELD node return node`). 

My plugin directory has:
```
graphaware-neo4j-to-elasticsearch-3.0.3.39.5-SNAPSHOT.jar
graphaware-server-community-all-3.0.3.39.jar
graphaware-uuid-3.0.3.39.10.jar
```
my config:

```

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.UIDM.node=(true)
com.graphaware.module.UIDM.relationship=(true)

#ES becomes the module ID:
com.graphaware.module.ES.2=com.graphaware.module.es.ElasticSearchModuleBootstrapper
com.graphaware.module.ES.uri=localhost
com.graphaware.module.ES.port=9200

#optional, Elasticsearch index name, default is neo2es-index
com.graphaware.module.ES.index=neo2es-index

#optional, whether to retry if a replication fails, defaults to false
com.graphaware.module.ES.retryOnError=false

com.graphaware.module.ES.node=(true)
com.graphaware.module.ES.relationship=(true)

#optional, specify which node properties to index in Elasticsearch, defaults to all properties
com.graphaware.module.ES.node.property=key != 'password'
com.graphaware.module.ES.relationship.property=key != 'password'

#optional, specify whether to send updates to Elasticsearch in bulk, defaults to true (highly recommended)
com.graphaware.module.ES.bulk=true

#optional, read explanation below, defaults to 0
com.graphaware.module.ES.initializeUntil=0

[...] 
# rest of the default neo4j config
```

**Comment by davidrapin** [comment]
@ikwattro I'm not sure how the ES procedures are registered in Neo4j 3.0 since `ElasticSearchProcedures.init` never seems to get called (I added a log message in the function locally, it never happens). Which is strange since the tests seem to work.

Shouldn't the procedures be declared with the `org.neo4j.procedure.Procedure` annotation instead, like in the UUID plugin?

**Comment by davidrapin** [comment]
@ikwattro tried to create the procedures the way it is done in the UUID plugin, build it and use it with Neo4j 3.0.3 local instance and it works ([see my branch](https://github.com/graphaware/neo4j-to-elasticsearch/compare/master...Linkurious:new-procedures)).

Thing is, the tests are broken now, any idea why?

**Comment by davidrapin** [comment]
Ok, all fixed now. I looked at how things were done in the UUID plugin for inspiration 😉

**Comment by davidrapin** [comment]
@ikwattro Can you confirm that this way of loading procedures works for you before I close this issue?

**Comment by davidrapin** [comment]
I guess that means yes ;)

**Comment by ikwattro** [comment]
It means I didn't really tried :/ btw the other version was working for me, which is weird. I'm happy for the changes and thanks you for all your contributions :)

**Comment by davidrapin** [comment]
Ok ! The most important is that it works now :) Thank you for your contributions as well ! Do you have a scheduled date for the release already ? Just to check when I should schedule to push our specific mapper !

**Comment by ikwattro** [comment]
Today or tomorrow, we will make sure the documentation is updated and make human testing on neo4j 3.0.3.

**Comment by davidrapin** [comment]
Ok!
