### ISSUE TITLE
ES port on the example neo4j server conf

### ISSUE THREAD

**Issue by RakshaAchuth** [graphaware/neo4j-to-elasticsearch#90]
Hi,

A very small comment: The port for ES in the server mode Neo4j.conf (which is given as example in the github loading page) might be wrong.

#Port of Elasticsearch
com.graphaware.module.ES.port=9201

I think that it should be 9200.

I hope that this is a useful thing to point out, to help new users avoid errors.

Cheers,

Raksha

**Comment by ikwattro** [comment]
The 9201 is intentional, because most people use default ports which is a serious security issue. Look on Google the number of elasticsearch instances reachable publicly
