### ISSUE TITLE
Way to control the Neo4j database size increasing due to data syncing to elasticsearch

### ISSUE THREAD

**Issue by Zhenshan-Jin** [graphaware/neo4j-to-elasticsearch#99]
Hi,

As the issue title said, it seems that the size of neo4j database increasing dramatically due to the elasticsearch syncing? In my case, the size goes up from 200MB to 1.13 GB. 

Since I want to deploy the database on the server, so the size would matter with the price that I pay for deploying the neo4j database. I'm wondering what kind of factors would influence the size increment, which I can control.

Thanks,

Zhenshan

**Comment by ikwattro** [comment]
There is nothing that influence the size of the db in this plugin. The internal queue is in-memory.
I believe the size you are seeing growing is the transaction logs.

**Comment by Zhenshan-Jin** [comment]
@ikwattro Thanks. By transaction logs, do you mean logs generated by neo4j or by plugins. Is there a way to specify the location where the log is generated? 

Find one in neo4j.conf: `dbms.directories.logs=/var/log/neo4j`

Thanks!

**Comment by ikwattro** [comment]
no, I mean the logs keeping your transaction data. They are generally in your `data/databases/graph.db/transactionxxx.log`, they serve for backups for example if you are on EE. If you are on community you can set the retention policy to false ( ref neo4j documentation )
